apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-ckqf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-ckqf
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-ckqf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-ckqf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-ckqf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-soxb-tenant/nodejs-users/simple-nodejs-app-ckqf@sha256:b65fab3364c5f5c11070ba10bdc75532c3ddc8c83b574c716dc5316adada6584
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
